# First-bake vulture allowlist. Add unused names here; do not delete this file.
job_by_id  # unused function (src/local_coding_slm/eval/jobs.py:114)
response_chars  # unused variable (src/local_coding_slm/eval/record.py:22)
exhausted  # unused variable (src/local_coding_slm/eval/record.py:34)
_.last_packet  # unused attribute (src/local_coding_slm/eval/review.py:69)
_.last_packet  # unused attribute (src/local_coding_slm/eval/review.py:77)
_.log_message  # unused method (src/local_coding_slm/eval/stub_ollama.py:82)
format  # unused variable (src/local_coding_slm/eval/stub_ollama.py:82)
_.do_GET  # unused method (src/local_coding_slm/eval/stub_ollama.py:93)
_.do_POST  # unused method (src/local_coding_slm/eval/stub_ollama.py:108)
local_status  # unused function (src/local_coding_slm/server.py:85)
local_code  # unused function (src/local_coding_slm/server.py:91)
local_refactor  # unused function (src/local_coding_slm/server.py:104)
local_generate_tests  # unused function (src/local_coding_slm/server.py:117)
local_explain  # unused function (src/local_coding_slm/server.py:132)
local_review  # unused function (src/local_coding_slm/server.py:145)
